/* ============================================================================
 * MoongCheap ERD v2.2 — 완성본 DDL (PostgreSQL)
 * ----------------------------------------------------------------------------
 * 원본: MoongCheap_erd_v2.sql (ERDCloud export)
 *
 * [원본 대비 변경 사항]
 *  0. [결제·주문 파트 소유 테이블] 아래 7개는 컬럼명·NULL 제약·DEFAULT 를 원본
 *     그대로 두고, 타입만 PostgreSQL 규격에 맞게 정정했다.
 *       GroupBuy / Payments / BrandpayPayMethod / PaymentsWebhock / Payout
 *       Orders / BrandPayToken
 *     정정 내역: LONG→BIGINT / STRING→VARCHAR(n)·TEXT / ENUM·EUNM→VARCHAR(30)
 *     ※ INT, BOOL, TIMESTAMP, JSON 은 PostgreSQL 유효 타입이므로 원본 그대로 둔
 *       곳이 있다 (각각 INTEGER, BOOLEAN, TIMESTAMP WITHOUT TIME ZONE, json 의 별칭)
 *     ※ 원본의 인라인 COMMENT '...' (MySQL 구문)는 SECTION 7 의
 *       COMMENT ON COLUMN 으로 이관했다.
 *
 *  1. (위 7개 제외) ERD 툴 의사 타입을 PostgreSQL 실제 타입으로 정규화
 *     LONG→BIGINT / STRING→VARCHAR·TEXT / INT→INTEGER / BOOL·EUNM 오타 수정
 *     ENUM→VARCHAR(30) (PostgreSQL ENUM 타입은 값 추가 시 마이그레이션 비용이
 *     크므로 VARCHAR + CHECK 로 대체. CHECK 는 파일 하단에 별도 블록으로 분리)
 *     TIMESTAMP→TIMESTAMPTZ (기존 TIMESTAMPTZ 컬럼과 혼용되어 있어 통일)
 *     JSON→JSONB
 *  2. PK 컬럼에 IDENTITY 부여 (원본은 채번 정의 없음)
 *     ※ 단, 아래 6개 테이블에는 IDENTITY 를 넣지 않았다. 애플리케이션에서 ID 를
 *       직접 발급해야 하며 JPA 의 @GeneratedValue(strategy = IDENTITY) 는 동작하지
 *       않는다. DB 채번으로 전환하려면 예:
 *         ALTER TABLE "Orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
 *       Orders / GroupBuy / Payments / BrandpayPayMethod / PaymentsWebhock / Payout
 *  3. 백틱(`) → 큰따옴표(") — PostgreSQL 식별자. 대소문자 혼용 테이블명
 *     (Orders, GroupBuy, Payments 등)을 원본 그대로 보존하기 위해 인용 유지
 *  4. ERD 메모에 기재된 UNIQUE / INDEX 전량 생성
 *  5. 누락된 FOREIGN KEY 전량 추가 (원본은 4건만 존재)
 *  6. NULL 제약 수정 — 아래 [NULL 제약 수정 내역] 참조
 *
 * [NULL 제약 수정 내역]  ※ 근거: 기능정의서 구매자 MVP V1
 *  demand.desired_price_min/max   NULL → NOT NULL   희망 가격대 필수 입력
 *  demand.quantity                NULL → NOT NULL   수량 필수 (1~99)
 *  demand.desire_end_at           NULL → NOT NULL   유효기간 7일, 접수 시 확정
 *  demand.is_substitutable        NULL → NOT NULL DEFAULT FALSE
 *                                                   3-state 방지 (미동의=FALSE)
 *  demand.status                  NULL → NOT NULL DEFAULT 'UNASSIGNED'
 *                                                   partial index 조건 컬럼
 *  demand_board.sale_end_at       NULL → NOT NULL   보드 생성 시점 +5일 확정
 *  shipping_address.is_default    NULL → NOT NULL DEFAULT FALSE
 *                                                   partial unique 조건 컬럼
 *
 * [수정하지 않고 남겨둔 항목 — 별도 검토 필요]
 *  · product.demand_board_id NOT NULL
 *      여분 즉시판매(ON_SALE/SOLD_OUT) 건이 수요보드 없이 존재 가능하면 NULL 필요.
 *      B-04 바로구매 TBD 상태이므로 확정 후 조정.
 *  · demand_board.status DEFAULT 'OPEN'
 *      기능정의서 상태값은 GB_GATHERING / GB_ACTION_REQUIRED / GB_CLOSED /
 *      GB_CANCELED. 메모의 index 조건도 'OPEN' 기준이라 원본 유지했으나 통일 필요.
 *  · Orders.group_buy_id / brandpay_id / shipping_number NOT NULL
 *      바로구매(INSTANT) 주문, 일반결제 주문, 배송 시작 전 주문을 표현할 수 없음.
 *  · Payments / Payout / SellerPayoutAccount / PaymentsWebhock
 *      식별자·상태·금액 컬럼이 대부분 NULL 허용. 결제 파트 담당자 검토 영역.
 *  · GroupBuy
 *      target_count·count·group_buy_end_at·status 가 product·demand_board 와 중복.
 *
 * [스키마에 아직 반영되지 않은 기능정의서 요구사항]
 *  · demand : 자동결제 동의 기록(auto_payment_agreed_at) — FN-B09-02
 *  · demand : 결제수단 연결 여부 — 확정 인원 집계 기준 (FN-B09-02 / B-03·B-08)
 *  · demand : 대체상품 제안 사유(reason) — FN-B16-01 '유사 상품으로 묶인 이유'
 *  · shipping_address : no_entrance_code — FN-B30-02 '공동현관번호 없어요' 체크
 * ========================================================================== */


/* ==========================================================================
 * SECTION 1. TABLE
 * ========================================================================== */

/* -------------------------------------------------- 회원 / 인증 */

CREATE TABLE "member" (
                          "id"              BIGINT        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          "login_id"        VARCHAR(20)   NULL,
                          "nickname"        VARCHAR(20)   NOT NULL,
                          "image"           VARCHAR(2048) NULL,
                          "phone_number"    TEXT          NULL,
                          "email"           VARCHAR(255)  NULL,
                          "is_seller"       BOOLEAN       NOT NULL DEFAULT FALSE,
                          "last_login_at"   TIMESTAMPTZ   NULL,
                          "created_at"      TIMESTAMPTZ   NOT NULL DEFAULT now(),
                          "updated_at"      TIMESTAMPTZ   NOT NULL DEFAULT now(),
                          "deleted_at"      TIMESTAMPTZ   NULL
);

CREATE TABLE "member_local" (
                                "id"                  BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                "member_id"           BIGINT       NOT NULL,
                                "password"            VARCHAR(255) NOT NULL,
                                "password_updated_at" TIMESTAMPTZ  NOT NULL DEFAULT now(),
                                "created_at"          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "member_social" (
                                 "id"          BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                 "member_id"   BIGINT       NOT NULL,
                                 "provider"    VARCHAR(20)  NOT NULL,
                                 "provider_id" VARCHAR(255) NOT NULL,
                                 "created_at"  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "seller" (
                          "id"                            BIGINT      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          "member_id"                     BIGINT      NOT NULL,
                          "business_name"                 VARCHAR(50) NOT NULL,
                          "business_number"               TEXT        NOT NULL,
                          "business_number_hash"          CHAR(64)    NOT NULL,
                          "mail_order_registration_number" VARCHAR(30) NOT NULL,
                          "owner_name"                    VARCHAR(50) NOT NULL,
                          "phone_number"                  VARCHAR(20) NOT NULL,
                          "seller_status"                 VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                          "approved_at"                   TIMESTAMPTZ NULL,
                          "created_at"                    TIMESTAMPTZ NOT NULL DEFAULT now(),
                          "updated_at"                    TIMESTAMPTZ NOT NULL DEFAULT now(),
                          "deleted_at"                    TIMESTAMPTZ NULL
);

/* -------------------------------------------------- 배송지 */

CREATE TABLE "shipping_address" (
                                    "id"              BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "member_id"       BIGINT       NOT NULL,
                                    "is_default"      BOOLEAN      NOT NULL DEFAULT FALSE,  -- [수정] NULL → NOT NULL
                                    "alias"           VARCHAR(30)  NOT NULL,
                                    "recipient_name"  VARCHAR(50)  NOT NULL,
                                    "phone_number"    TEXT         NOT NULL,
                                    "zipcode"         VARCHAR(5)   NOT NULL,
                                    "address"         VARCHAR(255) NOT NULL,
                                    "address_detail"  VARCHAR(100) NULL,
                                    "entrance_code"   VARCHAR(20)  NULL,
                                    "request_message" VARCHAR(100) NULL,
                                    "created_at"      TIMESTAMPTZ  NOT NULL DEFAULT now(),
                                    "updated_at"      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

/* -------------------------------------------------- 도감 / 수요 / 응찰 */

CREATE TABLE "product_catalog" (
                                   "id"            BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "name"          VARCHAR(100) NOT NULL,
                                   "spec_summary"  VARCHAR(500) NULL,
                                   "list_price"    INTEGER      NULL,
                                   "thumbnail_url" VARCHAR(255) NOT NULL,
                                   "description"   TEXT         NULL,
                                   "status"        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
                                   "created_at"    TIMESTAMPTZ  NOT NULL DEFAULT now(),
                                   "updated_at"    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "demand_board" (
                                "id"                BIGINT      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                "catalog_id"        BIGINT      NOT NULL,
                                "participant_count" INTEGER     NOT NULL DEFAULT 0,
                                "price_min"         INTEGER     NULL,
                                "price_max"         INTEGER     NULL,
                                "status"            VARCHAR(20) NOT NULL DEFAULT 'GB_GATHERING',
                                "judged_at"         TIMESTAMPTZ NULL,
                                "sale_end_at"       TIMESTAMPTZ NOT NULL,  -- [수정] NULL → NOT NULL
                                "created_at"        TIMESTAMPTZ NOT NULL DEFAULT now(),
                                "updated_at"        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "demand" (
                          "id"                BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          "demand_board_id"   BIGINT       NULL,   -- 미배정 상태에서는 NULL
                          "member_id"         BIGINT       NOT NULL,
                          "catalog_id"        BIGINT       NOT NULL,
                          "desired_price_max" INTEGER      NOT NULL,  -- [수정] NULL → NOT NULL
                          "desired_price_min" INTEGER      NOT NULL,  -- [수정] NULL → NOT NULL
                          "desire_end_at"     TIMESTAMPTZ  NOT NULL,  -- [수정] NULL → NOT NULL
                          "quantity"          INTEGER      NOT NULL,  -- [수정] NULL → NOT NULL
                          "extra_requirement" VARCHAR(200) NULL,
                          "is_substitutable"  BOOLEAN      NOT NULL DEFAULT FALSE,       -- [수정]
                          "status"            VARCHAR(20)  NOT NULL DEFAULT 'UNASSIGNED',-- [수정]
                          "label"             VARCHAR(200) NULL,   -- AI 클러스터링 라벨, 접수 시점엔 NULL
                          "processed_at"      TIMESTAMPTZ  NULL,   -- 클러스터링/낙찰 등 배치 처리 완료 시각
                          "created_at"        TIMESTAMPTZ  NOT NULL DEFAULT now(),
                          "updated_at"        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "product" (
                           "id"                      BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           "catalog_id"              BIGINT       NOT NULL,
                           "demand_board_id"         BIGINT       NOT NULL,
                           "seller_id"               BIGINT       NOT NULL,
                           "thumbnail_url"           VARCHAR(255) NULL,
                           "unit_price"              INTEGER      NOT NULL,
                           "shipping_fee"            INTEGER      NOT NULL DEFAULT 0,
                           "delivery_date"           DATE         NOT NULL,
                           "sale_end_at"             TIMESTAMPTZ  NOT NULL,
                           "total_quantity"          INTEGER      NOT NULL,
                           "min_participant_count"   INTEGER      NOT NULL,
                           "min_quantity"            INTEGER      NOT NULL,
                           "max_quantity_per_member" INTEGER      NULL,
                           "description"             TEXT         NULL,
                           "return_policy"           TEXT         NOT NULL,
                           "status"                  VARCHAR(20)  NOT NULL DEFAULT 'BIDDING',
                           "awarded_at"              TIMESTAMPTZ  NULL,
                           "closed_at"               TIMESTAMPTZ  NULL,
                           "created_at"              TIMESTAMPTZ  NOT NULL DEFAULT now(),
                           "updated_at"              TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "product_award_evaluation" (
                                            "id"              BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                            "product_id"      BIGINT       NOT NULL,
                                            "demand_board_id" BIGINT       NOT NULL,
                                            "score"           NUMERIC(5,4) NULL,
                                            "reason"          TEXT         NULL,
                                            "is_awarded"      BOOLEAN      NOT NULL,
                                            "judged_at"       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

/* -------------------------------------------------- 공동구매 */

/* [원본 유지] 결제·주문 파트 소유. 컬럼명·NULL·DEFAULT 는 원본 그대로, 타입만 정정 */
CREATE TABLE "GroupBuy" (
                            "id"	BIGINT	NOT NULL,
                            "title"	VARCHAR(255)	NOT NULL,
                            "target_count"	INT	NULL,
                            "count"	INT	NULL,
                            "group_buy_end_at"	TIMESTAMP	NULL,
                            "status"	VARCHAR(30)	NULL,
                            "seller_id"	BIGINT	NOT NULL,
                            "product_id"	BIGINT	NOT NULL
);

CREATE TABLE "GroupBuyLikes" (
                                 "groupbuy_id" BIGINT NOT NULL,
                                 "member_id"   BIGINT NOT NULL
);

/* -------------------------------------------------- 주문 / 결제 */

CREATE TABLE "Orders" (
                          "id"              BIGINT       NOT NULL,
                          "brandpay_id"     BIGINT       NOT NULL,
                          "customer_id"     BIGINT       NOT NULL,
                          "group_buy_id"    BIGINT       NOT NULL,
                          "idempotency_key" VARCHAR(255) NOT NULL,
                          "order_no"        VARCHAR(64)  NOT NULL,
                          "total_amount"    INTEGER      NOT NULL,
                          "product_id"      BIGINT       NULL,
                          "product_name"    VARCHAR(100) NOT NULL,
                          "sum"             INTEGER      NOT NULL,
                          "price"           INTEGER      NOT NULL,
                          "shipping_name"   VARCHAR(50)  NOT NULL,
                          "shipping_number" TEXT         NOT NULL,
                          "order_status"    VARCHAR(30)  NOT NULL,
                          "seller_id"       BIGINT       NOT NULL,
                          "business_name"   VARCHAR(50)  NOT NULL,
                          "zipcode"         VARCHAR(5)   NOT NULL,
                          "address"         VARCHAR(255) NOT NULL,
                          "address_detail"  VARCHAR(100) NOT NULL,
                          "image_url"       VARCHAR(255) NULL,
                          "created_at"      TIMESTAMPTZ  NOT NULL,
                          "updated_at"      TIMESTAMPTZ  NULL
);

/* [원본 유지] 타입만 정정 */
CREATE TABLE "Payments" (
                            "id"	BIGINT	NOT NULL,
                            "order_id"	BIGINT	NOT NULL,
                            "payment_key"	VARCHAR(200)	NULL	DEFAULT NULL,
                            "order_no"	VARCHAR(64)	NULL	DEFAULT NULL,
                            "order_name"	VARCHAR(255)	NULL	DEFAULT NULL,
                            "total_amount"	INT	NULL	DEFAULT NULL,
                            "payments_status"	VARCHAR(30)	NOT NULL	DEFAULT 'READY',
                            "payments_type"	VARCHAR(30)	NULL,
                            "method"	VARCHAR(30)	NULL,
                            "approvedAt"	TIMESTAMP	NULL,
                            "detail"	JSONB	NULL,
                            "created_at"	TIMESTAMP	NOT NULL,
                            "updated_at"	TIMESTAMP	NULL	DEFAULT NULL,
                            "canceled_at"	TIMESTAMP	NULL,
                            "cancel_reason"	VARCHAR(255)	NULL
);

/* [원본 유지] 타입만 정정 */
CREATE TABLE "PaymentsWebhock" (
                                   "id"	BIGINT	NOT NULL,
                                   "transmission_id"	VARCHAR(255)	NULL,
                                   "event_type"	VARCHAR(50)	NULL,
                                   "toss_created_at"	TIMESTAMP	NULL,
                                   "customer_key"	VARCHAR(50)	NULL,
                                   "method_key"	VARCHAR(255)	NULL,
                                   "payment_key"	VARCHAR(200)	NULL,
                                   "order_id"	VARCHAR(64)	NULL,
                                   "payload"	JSON	NULL,
                                   "received_at"	TIMESTAMP	NULL,
                                   "processed_at"	TIMESTAMP	NULL
);

/* [원본 유지] 타입만 정정 (원본 "type" 컬럼의 EUNM 오타 → VARCHAR) */
CREATE TABLE "BrandpayPayMethod" (
                                     "id"	BIGINT	NOT NULL,
                                     "member_id"	BIGINT	NOT NULL,
                                     "method_key"	VARCHAR(255)	NOT NULL,
                                     "provider_code"	VARCHAR(30)	NOT NULL,
                                     "masked_number"	VARCHAR(30)	NOT NULL,
                                     "type"	VARCHAR(30)	NULL,
                                     "is_default"	BOOL	NOT NULL,
                                     "status"	VARCHAR(30)	NOT NULL,
                                     "created_at"	TIMESTAMP	NOT NULL,
                                     "end_at"	TIMESTAMP	NULL,
                                     "password"	VARCHAR(10)	NULL,
                                     "cvc_num"	VARCHAR(10)	NULL
);

CREATE TABLE "CustomerKey" (
                               "member_id"    BIGINT       NOT NULL,
                               "customer_key" VARCHAR(50)  NOT NULL
);

CREATE TABLE "SellerKey" (
                             "seller_id"  BIGINT       NOT NULL,
                             "seller_key" VARCHAR(20)  NOT NULL
);

CREATE TABLE "BrandPayToken" (
                                 "member_id"               BIGINT      NOT NULL,
                                 "access_token"            TEXT        NULL,
                                 "refresh_token"           TEXT        NULL,
                                 "access_token_expires_at" TIMESTAMPTZ NULL
);

/* -------------------------------------------------- 정산 */

CREATE TABLE "SellerPayoutAccount" (
                                       "id"             BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       "seller_id"      BIGINT       NOT NULL,
                                       "pg_seller_key"  VARCHAR(35)  NULL,
                                       "businessType"   VARCHAR(30)  NULL,
                                       "status"         VARCHAR(30)  NULL,
                                       "bankCode"       VARCHAR(10)  NULL,
                                       "bank_account"   VARCHAR(50)  NULL,
                                       "depositor_name" VARCHAR(50)  NULL
);

/* [원본 유지] 타입만 정정 */
CREATE TABLE "Payout" (
                          "id"	BIGINT	NOT NULL,
                          "seller_id"	BIGINT	NOT NULL,
                          "ref_payout_Id"	VARCHAR(20)	NULL,
                          "pg_seller_key"	VARCHAR(35)	NULL,
                          "payout_date"	VARCHAR(20)	NULL,
                          "amount"	INT	NULL,
                          "request_at"	TIMESTAMP	NULL,
                          "status"	VARCHAR(30)	NULL
);

/* -------------------------------------------------- 알림 */

CREATE TABLE "notification_event" (
                                      "id"           BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      "type"         VARCHAR(40)  NOT NULL,
                                      "title"        VARCHAR(100) NOT NULL,
                                      "body"         VARCHAR(500) NOT NULL,
                                      "link_url"     VARCHAR(255) NULL,
                                      "is_mandatory" BOOLEAN      NOT NULL DEFAULT FALSE,
                                      "event_key"    VARCHAR(100) NOT NULL,
                                      "created_at"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
                                      "updated_at"   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "notification" (
                                "id"                    BIGINT      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                "notification_event_id" BIGINT      NOT NULL,
                                "member_id"             BIGINT      NOT NULL,
                                "is_read"               BOOLEAN     NOT NULL DEFAULT FALSE,
                                "read_at"               TIMESTAMPTZ NULL,
                                "created_at"            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "notification_opt_out" (
                                        "type"       VARCHAR(40) NOT NULL,
                                        "member_id"  BIGINT      NOT NULL,
                                        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);


/* ==========================================================================
 * SECTION 2. PRIMARY KEY
 * ========================================================================== */

ALTER TABLE "member"                   ADD CONSTRAINT "PK_MEMBER"                   PRIMARY KEY ("id");
ALTER TABLE "member_local"             ADD CONSTRAINT "PK_MEMBER_LOCAL"             PRIMARY KEY ("id");
ALTER TABLE "member_social"            ADD CONSTRAINT "PK_MEMBER_SOCIAL"            PRIMARY KEY ("id");
ALTER TABLE "seller"                   ADD CONSTRAINT "PK_SELLER"                   PRIMARY KEY ("id");
ALTER TABLE "shipping_address"         ADD CONSTRAINT "PK_SHIPPING_ADDRESS"         PRIMARY KEY ("id");
ALTER TABLE "product_catalog"          ADD CONSTRAINT "PK_PRODUCT_CATALOG"          PRIMARY KEY ("id");
ALTER TABLE "demand_board"             ADD CONSTRAINT "PK_DEMAND_BOARD"             PRIMARY KEY ("id");
ALTER TABLE "demand"                   ADD CONSTRAINT "PK_DEMAND"                   PRIMARY KEY ("id");
ALTER TABLE "product"                  ADD CONSTRAINT "PK_PRODUCT"                  PRIMARY KEY ("id");
ALTER TABLE "product_award_evaluation" ADD CONSTRAINT "PK_PRODUCT_AWARD_EVALUATION" PRIMARY KEY ("id");
ALTER TABLE "GroupBuy"                 ADD CONSTRAINT "PK_GROUPBUY"                 PRIMARY KEY ("id");
ALTER TABLE "Orders"                   ADD CONSTRAINT "PK_ORDERS"                   PRIMARY KEY ("id");
ALTER TABLE "Payments"                 ADD CONSTRAINT "PK_PAYMENTS"                 PRIMARY KEY ("id");
ALTER TABLE "PaymentsWebhock"          ADD CONSTRAINT "PK_PAYMENTSWEBHOCK"          PRIMARY KEY ("id");
ALTER TABLE "BrandpayPayMethod"        ADD CONSTRAINT "PK_BRANDPAYPAYMETHOD"        PRIMARY KEY ("id");
ALTER TABLE "CustomerKey"              ADD CONSTRAINT "PK_CUSTOMERKEY"              PRIMARY KEY ("member_id");
ALTER TABLE "SellerKey"                ADD CONSTRAINT "PK_SELLERKEY"                PRIMARY KEY ("seller_id");
ALTER TABLE "BrandPayToken"            ADD CONSTRAINT "PK_BRANDPAYTOKEN"            PRIMARY KEY ("member_id");
ALTER TABLE "SellerPayoutAccount"      ADD CONSTRAINT "PK_SELLERPAYOUTACCOUNT"      PRIMARY KEY ("id");
ALTER TABLE "Payout"                   ADD CONSTRAINT "PK_PAYOUT"                   PRIMARY KEY ("id");
ALTER TABLE "notification_event"       ADD CONSTRAINT "PK_NOTIFICATION_EVENT"       PRIMARY KEY ("id");
ALTER TABLE "notification"             ADD CONSTRAINT "PK_NOTIFICATION"             PRIMARY KEY ("id");
ALTER TABLE "notification_opt_out"     ADD CONSTRAINT "PK_NOTIFICATION_OPT_OUT"     PRIMARY KEY ("type", "member_id");

-- [추가] ERD 메모 '복합키 사용' 반영. 원본 SQL에 PK 정의 누락되어 있었음
ALTER TABLE "GroupBuyLikes"            ADD CONSTRAINT "PK_GROUPBUYLIKES"            PRIMARY KEY ("groupbuy_id", "member_id");


/* ==========================================================================
 * SECTION 3. UNIQUE  (ERD 메모 기반)
 * ========================================================================== */

/* -------- member : login_id / nickname (탈퇴 회원 제외) */
CREATE UNIQUE INDEX "uq_member_login_id"
    ON "member" ("login_id")
    WHERE "deleted_at" IS NULL;

CREATE UNIQUE INDEX "uq_member_nickname"
    ON "member" ("nickname")
    WHERE "deleted_at" IS NULL;

/* -------- member_local : 회원당 1건 */
ALTER TABLE "member_local"
    ADD CONSTRAINT "uq_member_local_member_id" UNIQUE ("member_id");

/* -------- member_social : 소셜 계정 중복 연동 방지 */
ALTER TABLE "member_social"
    ADD CONSTRAINT "uq_member_social_provider" UNIQUE ("provider", "provider_id");

/* -------- seller : 회원당 1건 / 사업자번호 해시 (탈퇴 판매자 제외) */
ALTER TABLE "seller"
    ADD CONSTRAINT "uq_seller_member_id" UNIQUE ("member_id");

CREATE UNIQUE INDEX "uq_seller_business_number_hash"
    ON "seller" ("business_number_hash")
    WHERE "deleted_at" IS NULL;

/* -------- shipping_address : 회원당 기본 배송지 1건 */
CREATE UNIQUE INDEX "uq_shipping_address_default"
    ON "shipping_address" ("member_id")
    WHERE "is_default" = TRUE;

/* -------- product_catalog : 도감 상품명 */
ALTER TABLE "product_catalog"
    ADD CONSTRAINT "uq_product_catalog_name" UNIQUE ("name");

/* -------- demand : 진행 중인 요청은 회원·도감상품당 1건
 * 종료(CLOSED) / 취소(CANCELED) / 소멸(EXPIRED) / 삭제(DELETED) 건은 제약 대상에서
 * 제외되므로 동일 상품 재접수가 가능하다. */
CREATE UNIQUE INDEX "uq_demand_member_catalog_active"
    ON "demand" ("member_id", "catalog_id")
    WHERE "status" IN ('UNASSIGNED', 'SUBSTITUTE_OFFERED', 'ASSIGNED');

/* -------- product : 판매자는 하나의 수요보드에 유효 응찰 1건 */
CREATE UNIQUE INDEX "uq_product_seller_board_active"
    ON "product" ("seller_id", "demand_board_id")
    WHERE "status" IN ('BIDDING', 'AWARDED', 'ON_SALE', 'SOLD_OUT');

/* -------- product_award_evaluation : 응찰당 판정 1건 */
ALTER TABLE "product_award_evaluation"
    ADD CONSTRAINT "uq_product_award_evaluation_product_id" UNIQUE ("product_id");

/* -------- notification : 회원·이벤트당 1건 */
ALTER TABLE "notification"
    ADD CONSTRAINT "uq_notification_member_event" UNIQUE ("member_id", "notification_event_id");

/* -------- notification_event : 이벤트 키 */
ALTER TABLE "notification_event"
    ADD CONSTRAINT "uq_notification_event_key" UNIQUE ("type", "event_key");

/* -------- 식별키 : 소비자·판매자 식별키는 전부 유니크 (ERD 메모) */
ALTER TABLE "CustomerKey"
    ADD CONSTRAINT "uq_customer_key" UNIQUE ("customer_key");

ALTER TABLE "SellerKey"
    ADD CONSTRAINT "uq_seller_key" UNIQUE ("seller_key");

/* -------- Orders : 주문번호 / 멱등키 (ERD 메모) */
ALTER TABLE "Orders"
    ADD CONSTRAINT "uq_orders_order_no" UNIQUE ("order_no");

ALTER TABLE "Orders"
    ADD CONSTRAINT "uq_orders_idempotency_key" UNIQUE ("idempotency_key");

/* -------- Payout : 지급 요청 식별자 (ERD 메모) */
CREATE UNIQUE INDEX "uq_payout_ref_payout_id"
    ON "Payout" ("ref_payout_Id")
    WHERE "ref_payout_Id" IS NOT NULL;


/* ==========================================================================
 * SECTION 4. INDEX  (ERD 메모 기반)
 * ========================================================================== */

/* -------- demand
 * 1. B-17 내 수요 참여 목록 (탭별 status 필터)
 * 2. 수요보드 참여자 조회 / 확정 인원 집계
 * 3. AI 클러스터링 대상 조회 (미배정 건)
 * 4. AI 클러스터링 라벨 (미배정 건)
 * 5. 미배정 2일 경과 만료 배치 */
CREATE INDEX "idx_demand_member_status"
    ON "demand" ("member_id", "status");

CREATE INDEX "idx_demand_board_id_assigned"
    ON "demand" ("demand_board_id")
    WHERE "status" = 'ASSIGNED';

CREATE INDEX "idx_demand_catalog_unassigned"
    ON "demand" ("catalog_id")
    WHERE "status" = 'UNASSIGNED';

CREATE INDEX "idx_demand_label_unassigned"
    ON "demand" ("label")
    WHERE "status" = 'UNASSIGNED';

CREATE INDEX "idx_demand_created_at_unassigned"
    ON "demand" ("created_at")
    WHERE "status" = 'UNASSIGNED';

/* -------- demand_board
 * ※ 원본 메모는 "category_id" 로 기재되어 있으나 demand_board 에 해당 컬럼이
 *    존재하지 않아 "catalog_id" 로 정정함 */
CREATE INDEX "idx_demand_board_catalog_open"
    ON "demand_board" ("catalog_id")
    WHERE "status" = 'OPEN';

CREATE INDEX "idx_demand_board_judged_at_open"
    ON "demand_board" ("judged_at")
    WHERE "status" = 'OPEN';

/* -------- product */
CREATE INDEX "idx_product_demand_board_id"
    ON "product" ("demand_board_id");

CREATE INDEX "idx_product_sale_end_at_onsale"
    ON "product" ("sale_end_at")
    WHERE "status" IN ('ON_SALE', 'SOLD_OUT');

CREATE INDEX "idx_product_seller_id"
    ON "product" ("seller_id");

/* -------- product_award_evaluation
 * ※ 원본 메모의 "demand_baord_id" 오타를 "demand_board_id" 로 정정 */
CREATE INDEX "idx_product_award_evaluation_board_id"
    ON "product_award_evaluation" ("demand_board_id");

/* -------- shipping_address */
CREATE INDEX "idx_shipping_address_member_id"
    ON "shipping_address" ("member_id");

/* -------- notification : 최신순 목록 조회 */
CREATE INDEX "idx_notification_member_id_desc"
    ON "notification" ("member_id", "id" DESC);


/* ==========================================================================
 * SECTION 5. FOREIGN KEY
 * ※ 원본에는 4건(CustomerKey / SellerKey / BrandPayToken / notification_opt_out)만
 *   정의되어 있어 나머지를 전량 추가함
 * ========================================================================== */

/* -------- 회원 / 인증 */
ALTER TABLE "member_local"        ADD CONSTRAINT "FK_member_TO_member_local"        FOREIGN KEY ("member_id")             REFERENCES "member" ("id");
ALTER TABLE "member_social"       ADD CONSTRAINT "FK_member_TO_member_social"       FOREIGN KEY ("member_id")             REFERENCES "member" ("id");
ALTER TABLE "seller"              ADD CONSTRAINT "FK_member_TO_seller"              FOREIGN KEY ("member_id")             REFERENCES "member" ("id");
ALTER TABLE "shipping_address"    ADD CONSTRAINT "FK_member_TO_shipping_address"    FOREIGN KEY ("member_id")             REFERENCES "member" ("id");

/* -------- 수요 / 응찰 */
ALTER TABLE "demand_board"        ADD CONSTRAINT "FK_product_catalog_TO_demand_board" FOREIGN KEY ("catalog_id")          REFERENCES "product_catalog" ("id");
ALTER TABLE "demand"              ADD CONSTRAINT "FK_demand_board_TO_demand"        FOREIGN KEY ("demand_board_id")       REFERENCES "demand_board" ("id");
ALTER TABLE "demand"              ADD CONSTRAINT "FK_member_TO_demand"              FOREIGN KEY ("member_id")             REFERENCES "member" ("id");
ALTER TABLE "demand"              ADD CONSTRAINT "FK_product_catalog_TO_demand"     FOREIGN KEY ("catalog_id")            REFERENCES "product_catalog" ("id");
ALTER TABLE "product"             ADD CONSTRAINT "FK_product_catalog_TO_product"    FOREIGN KEY ("catalog_id")            REFERENCES "product_catalog" ("id");
ALTER TABLE "product"             ADD CONSTRAINT "FK_demand_board_TO_product"       FOREIGN KEY ("demand_board_id")       REFERENCES "demand_board" ("id");
ALTER TABLE "product"             ADD CONSTRAINT "FK_seller_TO_product"             FOREIGN KEY ("seller_id")             REFERENCES "seller" ("id");
ALTER TABLE "product_award_evaluation" ADD CONSTRAINT "FK_product_TO_award_eval"    FOREIGN KEY ("product_id")            REFERENCES "product" ("id");
ALTER TABLE "product_award_evaluation" ADD CONSTRAINT "FK_demand_board_TO_award_eval" FOREIGN KEY ("demand_board_id")     REFERENCES "demand_board" ("id");

/* -------- 공동구매 */
ALTER TABLE "GroupBuy"            ADD CONSTRAINT "FK_seller_TO_GroupBuy"            FOREIGN KEY ("seller_id")             REFERENCES "seller" ("id");
ALTER TABLE "GroupBuy"            ADD CONSTRAINT "FK_product_TO_GroupBuy"           FOREIGN KEY ("product_id")            REFERENCES "product" ("id");
ALTER TABLE "GroupBuyLikes"       ADD CONSTRAINT "FK_GroupBuy_TO_GroupBuyLikes"     FOREIGN KEY ("groupbuy_id")           REFERENCES "GroupBuy" ("id");
ALTER TABLE "GroupBuyLikes"       ADD CONSTRAINT "FK_member_TO_GroupBuyLikes"       FOREIGN KEY ("member_id")             REFERENCES "member" ("id");

/* -------- 주문 / 결제 */
ALTER TABLE "Orders"              ADD CONSTRAINT "FK_member_TO_Orders"              FOREIGN KEY ("customer_id")           REFERENCES "member" ("id");
ALTER TABLE "Orders"              ADD CONSTRAINT "FK_GroupBuy_TO_Orders"            FOREIGN KEY ("group_buy_id")          REFERENCES "GroupBuy" ("id");
ALTER TABLE "Orders"              ADD CONSTRAINT "FK_product_TO_Orders"             FOREIGN KEY ("product_id")            REFERENCES "product" ("id");
ALTER TABLE "Orders"              ADD CONSTRAINT "FK_seller_TO_Orders"              FOREIGN KEY ("seller_id")             REFERENCES "seller" ("id");
ALTER TABLE "Orders"              ADD CONSTRAINT "FK_BrandpayPayMethod_TO_Orders"   FOREIGN KEY ("brandpay_id")           REFERENCES "BrandpayPayMethod" ("id");
ALTER TABLE "Payments"            ADD CONSTRAINT "FK_Orders_TO_Payments"            FOREIGN KEY ("order_id")              REFERENCES "Orders" ("id");
ALTER TABLE "BrandpayPayMethod"   ADD CONSTRAINT "FK_member_TO_BrandpayPayMethod"   FOREIGN KEY ("member_id")             REFERENCES "member" ("id");
ALTER TABLE "CustomerKey"         ADD CONSTRAINT "FK_member_TO_CustomerKey"         FOREIGN KEY ("member_id")             REFERENCES "member" ("id");
ALTER TABLE "SellerKey"           ADD CONSTRAINT "FK_seller_TO_SellerKey"           FOREIGN KEY ("seller_id")             REFERENCES "seller" ("id");
ALTER TABLE "BrandPayToken"       ADD CONSTRAINT "FK_member_TO_BrandPayToken"       FOREIGN KEY ("member_id")             REFERENCES "member" ("id");

/* -------- 정산 */
ALTER TABLE "SellerPayoutAccount" ADD CONSTRAINT "FK_seller_TO_SellerPayoutAccount" FOREIGN KEY ("seller_id")             REFERENCES "seller" ("id");
ALTER TABLE "Payout"              ADD CONSTRAINT "FK_seller_TO_Payout"              FOREIGN KEY ("seller_id")             REFERENCES "seller" ("id");

/* -------- 알림 */
ALTER TABLE "notification"         ADD CONSTRAINT "FK_notification_event_TO_notification" FOREIGN KEY ("notification_event_id") REFERENCES "notification_event" ("id");
ALTER TABLE "notification"         ADD CONSTRAINT "FK_member_TO_notification"       FOREIGN KEY ("member_id")             REFERENCES "member" ("id");
ALTER TABLE "notification_opt_out" ADD CONSTRAINT "FK_member_TO_notification_opt_out" FOREIGN KEY ("member_id")           REFERENCES "member" ("id");


/* ==========================================================================
 * SECTION 6. CHECK  (ENUM 대체 — 필요 시 적용)
 * ※ 원본 ENUM 타입 컬럼의 허용값을 CHECK 으로 표현.
 *   값 추가가 잦은 초기 단계라면 이 섹션 전체를 생략하고 애플리케이션에서 검증해도 됨
 * ========================================================================== */

ALTER TABLE "demand"       ADD CONSTRAINT "ck_demand_status"
    CHECK ("status" IN ('UNASSIGNED','SUBSTITUTE_OFFERED','ASSIGNED','CLOSED','CANCELED','EXPIRED','DELETED'));

ALTER TABLE "demand"       ADD CONSTRAINT "ck_demand_quantity"
    CHECK ("quantity" BETWEEN 1 AND 99);

ALTER TABLE "demand"       ADD CONSTRAINT "ck_demand_price_range"
    CHECK ("desired_price_min" <= "desired_price_max");

ALTER TABLE "product"      ADD CONSTRAINT "ck_product_status"
    CHECK ("status" IN ('BIDDING','AWARDED','ON_SALE','SOLD_OUT'));

/* SellerStatus — com.moongcheap_backend.member.domain.SellerStatus
 * ※ 원본 SQL 에는 REJECTED / SUSPENDED 로 기재되어 있었으나 실제 enum 에 맞춰 정정 */
ALTER TABLE "seller"       ADD CONSTRAINT "ck_seller_status"
    CHECK ("seller_status" IN ('PENDING','APPROVED','BLOCKED','WITHDRAWN'));

/* SocialProvider — com.moongcheap_backend.member.domain.SocialProvider */
ALTER TABLE "member_social" ADD CONSTRAINT "ck_member_social_provider"
    CHECK ("provider" IN ('KAKAO','GOOGLE'));

/* NotificationType — com.moongcheap_backend.notification.domain.NotificationType */
ALTER TABLE "notification_event" ADD CONSTRAINT "ck_notification_event_type"
    CHECK ("type" IN (
                      'DEMAND_REGISTERED','DEMAND_MERGED','RECRUIT_STATUS','BID_RESULT',
                      'PAYMENT_SCHEDULED','PAYMENT_COMPLETED','PAYMENT_FAILED','DELIVERY','CANCELED',
                      'BID_COMPETITION','BID_WON','BID_LOST','ORDER_CREATED','STOCK_DEPLETED'
        ));

/* 수신 거부는 mandatory = false 인 알림만 가능하므로 허용값을 좁힘.
 * mandatory 구분이 바뀌면 이 제약도 함께 갱신할 것 */
ALTER TABLE "notification_opt_out" ADD CONSTRAINT "ck_notification_opt_out_type"
    CHECK ("type" IN (
                      'DEMAND_REGISTERED','DEMAND_MERGED','RECRUIT_STATUS',
                      'BID_COMPETITION','BID_LOST','ORDER_CREATED','STOCK_DEPLETED'
        ));

ALTER TABLE "product_catalog" ADD CONSTRAINT "ck_product_catalog_status"
    CHECK ("status" IN ('ACTIVE','INACTIVE'));

/* ※ demand_board.status 는 기능정의서(GB_GATHERING / GB_ACTION_REQUIRED /
 *    GB_CLOSED / GB_CANCELED)와 현재 DEFAULT 'OPEN' 이 불일치하여 CHECK 미적용.
 *    값 체계 확정 후 아래 주석을 해제할 것
 * ALTER TABLE "demand_board" ADD CONSTRAINT "ck_demand_board_status"
 *     CHECK ("status" IN ('GB_GATHERING','GB_ACTION_REQUIRED','GB_CLOSED','GB_CANCELED'));
 */


/* ==========================================================================
 * SECTION 7. COMMENT  (원본 COMMENT 이관)
 * ========================================================================== */

COMMENT ON TABLE  "Orders" IS '주문은 결제 이전 공동구매에 참여할 때 생성된다. 주문번호(order_no)와 멱등키(idempotency_key)는 각각 유니크하다';
COMMENT ON COLUMN "Orders"."order_no"        IS '영문 대소문자, 숫자, 특수문자 -, _로 이루어진 6자 이상 64자 이하의 문자열';
COMMENT ON COLUMN "Orders"."sum"             IS '구매하는 상품의 수량';
COMMENT ON COLUMN "Orders"."price"           IS '상품의 개당 가격';
/* ※ 아래 COMMENT 는 원본 SQL 의 인라인 COMMENT '...' (MySQL 구문)를
 *    PostgreSQL 의 COMMENT ON COLUMN 으로 이관한 것 */
COMMENT ON COLUMN "GroupBuy"."status"        IS '공동구매 진행중, 인원 모집 완료(결제 대기), 전 인원 결제 완료, 공동구매 종료, 공동구매 실패, 공동구매 취소';
COMMENT ON COLUMN "Payments"."payment_key"   IS '200자 이하';
COMMENT ON COLUMN "Payments"."order_no"      IS '영문 대소문자, 숫자, 특수문자 -, _로 이루어진 6자 이상 64자 이하의 문자열';
COMMENT ON COLUMN "Payments"."order_name"    IS '구매 상품';
COMMENT ON COLUMN "Payments"."payments_status" IS 'READY(결제준비), IN_PROGRESS, DONE, CANCELED(결제취소)';
COMMENT ON COLUMN "Payments"."payments_type" IS 'NORMAL(일반결제), BILLING(자동결제), BRANDPAY(브랜드페이)';
COMMENT ON COLUMN "Payments"."method"        IS '카드, 가상계좌, 간편결제, 휴대폰, 계좌이체, 문화상품권, 도서문화상품권, 게임문화상품권';
COMMENT ON COLUMN "Payments"."detail"        IS '세부데이터를 통으로 저장';
COMMENT ON COLUMN "BrandpayPayMethod"."masked_number" IS '저장할때 앞에서 4자리만 저장';
COMMENT ON COLUMN "BrandpayPayMethod"."type"     IS '카드, 계좌';
COMMENT ON COLUMN "BrandpayPayMethod"."end_at"   IS 'MVP에서만 사용';
COMMENT ON COLUMN "BrandpayPayMethod"."password" IS '앞 2자리만 / MVP에서만 사용';
COMMENT ON COLUMN "BrandpayPayMethod"."cvc_num"  IS 'MVP에서만 사용';
COMMENT ON COLUMN "Payout"."ref_payout_Id"   IS '최대 50자';
COMMENT ON COLUMN "Payout"."status"          IS 'REQUESTED(지급 요청됨, 이 상태에서만 취소 가능) / IN_PROGRESS(처리 중) / COMPLETED(지급 완료) / FAILED(요청 실패) / CANCELED(요청 취소) / REJECTED(요청 반려, 웹훅은 FAILED 로 발송)';
COMMENT ON COLUMN "SellerPayoutAccount"."pg_seller_key" IS 'PG사에 판매자를 등록하면 PG사가 발급';


/* --------------------------------------------------------------------------
 * 도메인 테이블 컬럼 설명
 * -------------------------------------------------------------------------- */

/* -------- product_catalog : 상품 도감 */
COMMENT ON TABLE  "product_catalog"          IS '상품 도감. 구매자가 수요를 접수하는 기준 단위';
COMMENT ON COLUMN "product_catalog"."status" IS 'ACTIVE(도감 노출·수요 접수 가능) / INACTIVE(노출 중단). 검색·홈 목록은 ACTIVE 만 대상';
COMMENT ON COLUMN "product_catalog"."list_price"   IS '정가. 수요보드 희망 가격대 대비 절감액 표시 기준';
COMMENT ON COLUMN "product_catalog"."spec_summary" IS '도감 기준 스펙 요약. 상품 카드·상세의 스펙 표에 노출';

/* -------- demand : 개별 수요 요청 */
COMMENT ON TABLE  "demand" IS '구매자 1인의 수요 요청 1건. 공구의 생애주기(낙찰·결제 확인 등)는 demand_board 가 소유하며, 이 테이블은 요청이 어디에 속했고 살아있는지만 관리한다';
COMMENT ON COLUMN "demand"."status" IS 'UNASSIGNED(미배정 — 클러스터 편입 대기, 최대 2일) / SUBSTITUTE_OFFERED(대체상품 제안 — 유사 상품 클러스터 편입 제안에 대한 응답 대기) / ASSIGNED(배정완료 — 수요보드 편입, 진행 중) / CLOSED(종료 — 소속 보드가 GB_CLOSED 도달, 주문 생성 완료) / CANCELED(사용자 취소 — 참여 취소 MVP 포함 여부 확정 대기) / EXPIRED(소멸 — 미배정 2일 경과, 클러스터 생성 실패, 제안 무응답) / DELETED(운영자·시스템 무효화). UNASSIGNED·SUBSTITUTE_OFFERED·ASSIGNED 3종만 진행 중으로 보며 중복 접수 UNIQUE 대상이다';
COMMENT ON COLUMN "demand"."demand_board_id" IS '미배정 상태에서는 NULL. SUBSTITUTE_OFFERED 시 제안 대상 보드 ID 를 선반영하고, 수락 시 그대로 확정 / 거절 시 NULL 로 복귀';
COMMENT ON COLUMN "demand"."is_substitutable" IS '대체 상품 추천 동의 여부. FALSE 인 건은 원 상품만으로 구성된 클러스터에만 편입되며 대체상품 제안 대상에서 제외된다';
COMMENT ON COLUMN "demand"."desired_price_min" IS '희망 가격대 하한. 접수 시 7개 구간 중 1건 선택';
COMMENT ON COLUMN "demand"."desired_price_max" IS '희망 가격대 상한. 낙찰가는 이 값을 초과할 수 없다';
COMMENT ON COLUMN "demand"."quantity"          IS '요청 수량(1~99). 대체상품 수락 시에도 원 요청 수량을 그대로 승계하며 변경 불가';
COMMENT ON COLUMN "demand"."desire_end_at"     IS '요청 유효기간 만료 시각. 접수 시점부터 7일(미배정 대기 2일 + 프로세싱 5일)';
COMMENT ON COLUMN "demand"."extra_requirement" IS '자연어 추가 조건(선택). 클러스터링·낙찰 판정 참고용';
COMMENT ON COLUMN "demand"."label"             IS 'AI 클러스터링 라벨. 접수 직후에는 NULL 이며 UNASSIGNED 건에만 부여된다';

/* -------- demand_board : 수요 클러스터(공구) */
COMMENT ON TABLE  "demand_board" IS '유사 수요 요청을 묶은 클러스터. 판매자는 이 보드를 보고 product(응찰)를 생성하며, 목표 수량·최소 인원 등의 판매 조건은 product 가 소유한다';
COMMENT ON COLUMN "demand_board"."status" IS '현재 DEFAULT 는 OPEN 이나, 기능정의서의 공구 상태값은 GB_GATHERING(모이는 중 — 응찰 접수 및 참여자 모집) / GB_ACTION_REQUIRED(확인 필요 — 낙찰 확정, 참여자별 48시간 결제 확인) / GB_CLOSED(종료 — 전원 결제 완료, 주문 생성) / GB_CANCELED(취소 — MVP 에서는 클러스터 생성 후 실패 경로가 없어 도달하지 않음) 4종이다. 값 체계 통일 필요 (SECTION 6 의 ck_demand_board_status 주석 참조)';
COMMENT ON COLUMN "demand_board"."participant_count" IS '확정 참여 인원 캐시. 결제수단이 연결된 확정 수요만 집계한다';
COMMENT ON COLUMN "demand_board"."price_min" IS '편입된 요청들의 희망 가격대로 산출한 하한';
COMMENT ON COLUMN "demand_board"."price_max" IS '편입된 요청들의 희망 가격대로 산출한 상한. 낙찰가 검증 기준';
COMMENT ON COLUMN "demand_board"."judged_at"   IS '낙찰 판정 시각. 참여자별 48시간 결제 기한의 기산점';
COMMENT ON COLUMN "demand_board"."sale_end_at" IS '모집 마감 시각. 보드 생성 시점부터 5일(프로세싱 기간)';

/* -------- product : 판매자 응찰 / 판매 상품 */
COMMENT ON TABLE  "product" IS '판매자가 수요보드를 보고 등록한 응찰. 낙찰 후에는 판매 상품으로 전환된다';
COMMENT ON COLUMN "product"."status" IS 'BIDDING(응찰 — 낙찰 판정 대기) / AWARDED(낙찰 — 해당 보드의 최종 낙찰 응찰) / ON_SALE(판매 중 — 여분 즉시판매) / SOLD_OUT(품절). 4종 모두 UNIQUE(seller_id, demand_board_id) 대상이므로 판매자는 한 보드에 유효 응찰 1건만 보유한다';
COMMENT ON COLUMN "product"."min_participant_count"   IS '판매자가 설정한 최소 참여자 수. 이미 모인 인원으로 충족 가능한 값만 설정하도록 응찰 시점에 검증한다';
COMMENT ON COLUMN "product"."min_quantity"            IS '판매자가 설정한 최소 주문 수량';
COMMENT ON COLUMN "product"."max_quantity_per_member" IS '1인당 최대 주문 수량. NULL 이면 제한 없음';
COMMENT ON COLUMN "product"."total_quantity"          IS '판매 가능 총 수량';
COMMENT ON COLUMN "product"."unit_price"              IS '응찰 단가. 낙찰 시 결제 단가가 되며 보드 희망 가격대 상한을 초과할 수 없다';
COMMENT ON COLUMN "product"."awarded_at"              IS '낙찰 확정 시각';
COMMENT ON COLUMN "product"."closed_at"               IS '판매 종료 시각';

/* -------- product_award_evaluation : 낙찰 판정 */
COMMENT ON TABLE  "product_award_evaluation"        IS 'AI 낙찰 판정 결과. 응찰 1건당 1행';
COMMENT ON COLUMN "product_award_evaluation"."is_awarded" IS 'TRUE = 최종 낙찰. 보드당 TRUE 는 1건이어야 하며 이는 애플리케이션에서 보장한다';
COMMENT ON COLUMN "product_award_evaluation"."score"     IS 'AI 적합도 점수(0~1)';
COMMENT ON COLUMN "product_award_evaluation"."reason"    IS 'AI 판단 사유. 낙찰 결과 화면(B-19)의 낙찰 근거로 노출';

/* -------- shipping_address : 배송지 */
COMMENT ON TABLE  "shipping_address"           IS '회원별 배송지. 계정당 최대 5건까지 등록 가능하며(SHIP_002), 주문 시에는 SNAPSHOT 으로 복사되므로 삭제는 물리 삭제로 처리한다';
COMMENT ON COLUMN "shipping_address"."is_default"      IS '기본 배송지 여부. 회원당 TRUE 는 1건(부분 UNIQUE 로 강제)';
COMMENT ON COLUMN "shipping_address"."alias"           IS '배송지 별칭 (예: 집, 회사)';
COMMENT ON COLUMN "shipping_address"."entrance_code"   IS '공동현관번호(선택). 미입력과 "공동현관번호 없음" 을 구분하려면 no_entrance_code 컬럼 추가 필요';
COMMENT ON COLUMN "shipping_address"."request_message" IS '배송 요청 메시지';

/* -------- member : 회원 */
COMMENT ON TABLE  "member" IS '회원 공통 정보. 로그인 수단은 member_local(자체) / member_social(소셜)로 분리되며, 최소 1개의 로그인 수단이 유지되어야 한다(AUTH_012)';
COMMENT ON COLUMN "member"."is_seller"  IS '판매자 전환 여부. MemberRole 은 이 값으로 파생된다 — FALSE=BUYER(일반 구매자) / TRUE=SELLER(판매자). Spring Security 인증 권한으로 사용';
COMMENT ON COLUMN "member"."login_id"   IS '자체 로그인 아이디. 소셜 전용 회원은 NULL';
COMMENT ON COLUMN "member"."deleted_at" IS '탈퇴 시각(soft delete). login_id·nickname UNIQUE 는 이 값이 NULL 인 행만 대상';

/* -------- member_local : 자체 로그인 자격증명 */
COMMENT ON TABLE  "member_local" IS '자체 로그인(아이디·비밀번호) 자격증명. 회원당 1건';
COMMENT ON COLUMN "member_local"."password"            IS '해시된 비밀번호';
COMMENT ON COLUMN "member_local"."password_updated_at" IS '비밀번호 최종 변경 시각';

/* -------- member_social : 소셜 로그인 연동 */
COMMENT ON TABLE  "member_social"             IS '소셜 로그인 연동 정보. 하나의 소셜 계정은 한 회원에만 연동될 수 있다';
COMMENT ON COLUMN "member_social"."provider"    IS 'SocialProvider — KAKAO(카카오 OAuth2) / GOOGLE(구글 OAuth2)';
COMMENT ON COLUMN "member_social"."provider_id" IS '소셜 제공자가 발급한 사용자 고유 식별자';

/* -------- seller : 판매자 */
COMMENT ON TABLE  "seller" IS '판매자 등록 정보. 회원당 1건이며, 응찰 등 판매 기능은 seller_status = APPROVED 인 경우에만 허용된다(SELLER_008)';
COMMENT ON COLUMN "seller"."seller_status" IS 'SellerStatus — PENDING(등록 신청 후 관리자 심사 대기) / APPROVED(심사 완료, 정상 영업 가능) / BLOCKED(관리자에 의한 판매 차단) / WITHDRAWN(판매자 자진 탈퇴, softDelete 수행). 전이: PENDING→APPROVED(승인), APPROVED→BLOCKED(차단), APPROVED→WITHDRAWN(탈퇴)';
COMMENT ON COLUMN "seller"."approved_at"          IS '관리자 승인 시각. PENDING 상태에서는 NULL';
COMMENT ON COLUMN "seller"."business_number"      IS '사업자등록번호 원문(암호화 저장 대상)';
COMMENT ON COLUMN "seller"."business_number_hash" IS '사업자등록번호 해시. 중복 등록 판정용';
COMMENT ON COLUMN "seller"."deleted_at"           IS '탈퇴 시각(soft delete). WITHDRAWN 전이 시 기록';

/* -------- notification_event : 알림 이벤트 원본 */
COMMENT ON TABLE  "notification_event" IS '알림 이벤트 원본. 여러 회원에게 발송되는 동일 알림의 본문을 1건으로 보관한다';
COMMENT ON COLUMN "notification_event"."type" IS 'NotificationType. [구매자] DEMAND_REGISTERED(수요 등록) / DEMAND_MERGED(수요 병합) / RECRUIT_STATUS(모집 현황) / BID_RESULT(낙찰 결과) / PAYMENT_SCHEDULED(결제 예정) / PAYMENT_COMPLETED(결제 완료) / PAYMENT_FAILED(결제 실패) / DELIVERY(배송) / CANCELED(무산). [판매자] BID_COMPETITION(응찰 경쟁 현황) / BID_WON(낙찰) / BID_LOST(미낙찰) / ORDER_CREATED(주문 발생) / STOCK_DEPLETED(재고 소진)';
COMMENT ON COLUMN "notification_event"."is_mandatory" IS 'TRUE = 수신 거부 불가 알림. 해당 type 은 notification_opt_out 에 등록될 수 없다. 필수 알림: BID_RESULT, PAYMENT_SCHEDULED, PAYMENT_COMPLETED, PAYMENT_FAILED, DELIVERY, CANCELED, BID_WON';
COMMENT ON COLUMN "notification_event"."event_key" IS '이벤트 멱등키. 동일 사건에 대한 중복 알림 생성을 방지한다';
COMMENT ON COLUMN "notification_event"."link_url"  IS '알림 탭 시 이동할 딥링크. 없으면 이동 없음';

/* -------- notification : 회원별 수신 알림 */
COMMENT ON TABLE  "notification"            IS '회원별 알림 수신 내역. 회원·이벤트 조합당 1건';
COMMENT ON COLUMN "notification"."is_read"  IS '읽음 여부';
COMMENT ON COLUMN "notification"."read_at"  IS '읽은 시각. 미열람 시 NULL';

/* -------- notification_opt_out : 알림 수신 거부 */
COMMENT ON TABLE  "notification_opt_out"         IS '알림 종류별 수신 거부 설정. 행이 존재하면 해당 type 을 수신하지 않는다(옵트아웃 방식)';
COMMENT ON COLUMN "notification_opt_out"."type"  IS '수신 거부한 NotificationType. is_mandatory = TRUE 인 필수 알림은 등록할 수 없으며, 허용값은 DEMAND_REGISTERED, DEMAND_MERGED, RECRUIT_STATUS, BID_COMPETITION, BID_LOST, ORDER_CREATED, STOCK_DEPLETED';
COMMENT ON COLUMN "SellerPayoutAccount"."businessType"  IS 'INDIVIDUAL(개인), INDIVIDUAL_BUSINESS(개인사업자), CORPORATE(법인사업자)';