CREATE TABLE "category" (
    "id"         BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "parent_id"  BIGINT       NULL,
    "name"       VARCHAR(50)  NOT NULL,
    "depth"      SMALLINT     NOT NULL,
    "facet"      TEXT         NULL,
    "created_at" TIMESTAMPTZ  NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE "category" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("id");

ALTER TABLE "category" ADD CONSTRAINT "FK_category_TO_category" FOREIGN KEY ("parent_id") REFERENCES "category" ("id");

CREATE UNIQUE INDEX "uq_category_parent_name"
    ON "category" (COALESCE("parent_id", 0), "name");
